export const teacher_routes = {
  teacherDashboard: "/teacher-dashboard",

  blankPage: "/blank-page",
  calendar: "/calendar",
  dataTables: "/data-tables",
  tablesBasic: "/tables-basic",
  notes: "/notes",
  comingSoon: "/coming-soon",

  // application routes
  todo: "/application/todo",
  email: "/application/email",
  videoCall: "/application/video-call",
  chat: "/application/chat",
  audioCall: "/application/audio-call",
  callHistory: "/application/call-history",
  fileManager: "/application/file-manager",

  // Peoples Module
  studentGrid: "/teacher/students/student-grid",
  studentPromotion: "/teacher/students/student-promotion",
  //   studentOnboarding: "/student/student-onboarding",
  studentDetail: "/teacher/students/student-details",
  //   studentTimeTable: "/student/student-time-table",
  studentLeaves: "/teacher/student/student-leaves",
  //   studentFees: "/student/student-fees",
  //   studentResult: "/student/student-result",
  studentLibrary: "/teacher/student/student-library",
  studentList: "/teacher/students/student-list",
  //   addStudent: "/student/add-student",
  //   editStudent: "/student/edit-student",
  teacherDetails: "/teacher/students/teacher-details",
  //   teacherGrid: "/teacher/teacher-grid",
  //   teacherList: "/teacher/teacher-list",
  //   addTeacher: "/teacher/add-teacher",
  //   editTeacher: "/teacher/edit-teacher",
  //   teacherLibrary: "/teacher/teacher-library",
  //   teacherSalary: "/teacher/teacher-salary",
  //   teacherLeaves: "/teacher/teacher-leaves",
  //   teachersRoutine: "/teacher/teacher-routine",
  parentGrid: "/teacher/parent/parent-grid",
  parentList: "/teacher/parent/parent-list",
  guardiansGrid: "/teacher/parent/guardians-grid",
  guardiansList: "/teacher/parent/guardians-list",

  // Management
  //   feesGroup: "/management/fees-group",
  //   feesType: "/management/fees-type",
  //   feesMaster: "/management/fees-master",
  feesAssign: "/teacher/management/fees-assign",
  //   collectFees: "/management/collect-fees",
  //   libraryMembers: "/management/library-members",
  libraryIssueBook: "/teacher/management/library-issue-book",
  //   libraryBooks: "/management/library-books",
  libraryReturn: "/teacher/management/library-return",
  playerList: "/teacher/management/players",
  sportsList: "/teacher/management/sports",
  //   hostelList: "/management/hostel-list",
  //   hostelType: "/management/hostel-type",
  //   hostelRoom: "/management/hostel-rooms",
  //   transportAssignVehicle: "/management/transport-assign-vehicle",
  //   transportVehicle: "/management/transport-vehicle",
  //   transportVehicleDrivers: "/management/transport-vehicle-drivers",
  //   transportPickupPoints: "/management/transport-pickup-points",
  //   transportRoutes: "/management/transport-routes",

  //Academic module
  //   AcademicReason: "/teacher/academic/academic-reason",
  classSyllabus: "/teacher/academic/class-syllabus",
  classSubject: "/teacher/academic/class-subject",
  classSection: "/teacher/academic/class-section",
  classRoom: "/teacher/academic/class-room",
  classRoutine: "/teacher/academic/class-routine",
  sheduleClasses: "/teacher/academic/schedule-classes",
  classes: "/teacher/academic/classes-section",
  classHomeWork: "/teacher/academic/class-home-work",
  exam: "/teacher/academic/exam",
  examSchedule: "/teacher/academic/exam-schedule",
  grade: "/teacher/academic/grade",
  examResult: "/teacher/academic/exam-result",
  updateExamResult: "/teacher/academic/update-exam-result",
  examAttendance: "/teacher/academic/exam-attendance",
  classTimetable: "/teacher/academic/class-time-table",

  //Hrm module
  //   staff: "/hrm/staff",
  //   departments: "/hrm/departments",
  //   payroll: "/hrm/payroll",
  holidays: "/teacher/hrm/holidays",
  //   designation: "/hrm/designation",
  //   listLeaves: "/hrm/list-leaves",
  //   staffDetails: "/hrm/staff-details",
  //   staffPayroll: "/hrm/staff-payroll",
  //   staffLeave: "/hrm/staff-leave",

  //   approveRequest: "/hrm/approve-request",
  studentAttendance: "/teacher/hrm/student-attendance",
  //   teacherAttendance: "/hrm/teacher-attendance",
  //   staffAttendance: "/hrm/staff-attendance",
  //   addStaff: "/hrm/add-staff",
  //   editStaff: "/hrm/edit-staff",
  //   staffsAttendance: "/hrm/staffs-attendance",
};
